config/routes.rb
WSOonRails::Application.routes.draw do

  resources :api_keys, only: :create

  # SESSIONS
  get  'account/login',      to: 'account#login_page'
  post 'account/login',      to: 'account#login',      as: :login
  get  'account/logout',     to: 'account#logout',     as: :logout

  # INDEX
  root  'front#index'
  match '/search',   to: 'front#search', via: [:get, :post]


  # FACEBOOK
  get  'facebook',                  to: 'facebook#index'
  post 'facebook',                  to: 'facebook#index'
  get 'facebook/edit',             to: 'facebook#edit'
  get 'facebook/help',              to: 'facebook#help'
  get 'facebook/view/:unix_id',    to: 'facebook#view'

  scope '/facebook' do
    resources :students, only: [:show, :edit, :update], controller: 'users', path: 'users'
    resources :professors, only: [:show, :edit, :update], controller: 'users', path: 'users'
    resources :staff, only: [:show, :edit, :update], controller: 'users', path: 'users'
    resources :alum, only: [:show, :edit, :update], controller: 'users', path: 'users'
  end


  # EPHCATCH
  get "/ephcatch", to: "ephcatch#index"
  scope "/ephcatch" do
    resources :ephcatches, controller: "ephcatch", path: "ephcatches"
    get 'matches', to: 'ephcatch#matches'
  end

  # BULLETINS
  resources :bulletins
  scope module: 'bulletins' do
    resources :announcements
    resources :discussions
    resources :posts
    resources :exchanges
    resources :jobs
    resources :lost_founds, path: "lost_and_found"
    resources :rides
  end
  resources :bulletins

  get 'bulletins', to: 'bulletins#index'

  # FACTRAK
  get  '/factrak',                         to: 'factrak#index'
  get  '/factrak/autocomplete',            to: 'factrak#autocomplete', as: 'autocomplete'
  get  '/factrak/find_depts_autocomplete', to: 'factrak#find_depts_autocomplete'
  get  '/factrak/moderate',                to: 'factrak#moderate'
  post '/factrak/search',                  to: 'factrak#search'
  post '/factrak/accept_policy',           to: 'factrak#accept_policy'
  get  '/factrak/policy',                  to: 'factrak#policy'
  get  '/factrak/flag',                    to: 'factrak#flag'
  get  '/factrak/unflag',                  to: 'factrak#unflag'

  namespace :factrak do
    resources :courses
    resources :areas_of_study
    resources :professors
    resources :factrak_agreements, path: '/agreements', as: 'agreements'
    resources :factrak_surveys,    path: '/surveys',    as: 'surveys'
  end


  # ABOUT
  get '/about', to: 'about#index'
  scope '/about' do
    get 'welcome', to: 'about#welcome'
    get 'listserv', to: 'about#listserv'
  end


  # DORMTRAK
  get  '/dormtrak',               to: 'dormtrak#index'
  post '/dormtrak/search',        to: 'dormtrak#search'
  get  '/dormtrak/policy',        to: 'dormtrak#policy'
  post '/dormtrak/accept_policy', to: 'dormtrak#accept_policy'

  namespace :dormtrak do
    # the reviews route is a little hacky trick. it allows dormtrak_review_path
    # because dormtrak_review becomes just reviews and everything is prepended
    # with the namespace dormtrak. So, it is really dormtrak..review_path, but
    # it looks like dormtrak_review..path :) so no dormtrak_dormtrak_review_path
    # which is ridiculous
    resources :dormtrak_reviews, path: '/reviews', as: 'reviews'
    resources :dorms, only: [:index, :show, :update]
    resources :neighborhoods, path: 'hoods', only: [:index, :show, :update]
  end

end

app/models/bulletin.rb
class Bulletin < ActiveRecord::Base

  belongs_to :user

  validates :user, presence: true
  validates :title, presence: true, allow_blank: false

  # Everything other than ride will NOT have these
  # Note the special handling of boolean presence
  validates :offer, exclusion: { in: [true, false] }, unless: :ride?
  validates :offer, :source, :destination, absence: true, unless: :ride?

  before_save :normalize_start_date

  def self.latest(n)
    Bulletin.where("start_date <= ?", Date.today).last(n)
  end

  def ride?
    self.type == "Ride"
  end

  def self.title
    self.name.pluralize
  end

  def show_date
    start_date
  end

  private

  # User might assign something like Feb 1 when it is currently Oct,
  # and so we want it to use next year's feb 1, not this year's
  # It ||'s with Time.zone.now to allow for fine-grained tiebreaking
  def normalize_start_date
    self.start_date ||= Time.zone.now
    if self.start_date.to_date == Date.today
      self.start_date = Time.zone.now
    end
    self.start_date += 1.year if self.start_date < Date.today
    true
  end
end

app/controllers/bulletins/announcements_controller.rb
class Bulletins::AnnouncementsController < BulletinsController

  before_action :ensure_user, :only => [:new, :create, :edit]

  # GET /announcements
  # GET /announcements.json
  def index
    @bulletins = Announcement.alive.paginate(page: params[:page])

    respond_to do |format|
      format.html { render template: 'bulletins/shared/index' }
      format.json { render json: Announcement.all }
    end
  end

  # GET /announcements/new
  # GET /announcements/new.json
  def new
    @bulletin = @current_user.announcements.build
    super
  end

  # POST /announcements
  # POST /announcements.json
  def create
    @bulletin = current_user.announcements.build(bulletin_params)
    super
  end

  private

  def set_page_class
    @page_class = Announcement
  end

  # Note that this is also used in BulletinsController
  def bulletin_params
    params.require(:announcement).permit(:title,
                                         :body,
                                         :start_date)
  end

end

app/controllers/bulletins/discussions_controller.rb
class Bulletins::DiscussionsController < ApplicationController
  before_action :ensure_user

  require 'will_paginate/array'

  layout 'discussions'

  def index
    @threads = Discussion.alive.paginate(page: params[:page], per_page: 20)

    respond_to do |format|
      format.json { render json: Discussion.alive }
      format.html { render :index }
    end
  end

  def show
    @thread = Discussion.find(params[:id])
    @posts = @thread.children
    @reply = Post.new

    respond_to do |format|
      format.json { render json: @thread.to_json(include: [:posts])}
      format.html { render :show }
    end

  end

  # Users don't create threads. They create Posts, and depending on the
  # context in which the Post was created, we might auto-create a Thread
  def new
    @thread = Discussion.new
    @post = Post.new
  end

  def destroy
    d = Discussion.find(params[:id])
    d.update_attributes(deleted: true) if current_user.admin?
    redirect_to "/discussions"
  end

end

app/controllers/bulletins/exchanges_controller.rb
class Bulletins::ExchangesController < BulletinsController

  before_action :ensure_user, :only => [:new, :create, :edit]

  def index
    @bulletins = Exchange.paginate(page: params[:page])

    respond_to do |format|
      format.json { render json: Exchange.all }
      format.html { render template: 'bulletins/shared/index' }
    end
  end

  # GET /exchanges/new
  # GET /exchanges/new.json
  def new
    @bulletin = @current_user.exchanges.build
    super
  end

  # POST /exchanges
  # POST /exchanges.json
  def create
    @bulletin = current_user.exchanges.build(bulletin_params)
    super
  end

  private

  def set_page_class
    @page_class = Exchange
  end

  # Note that this is also used in BulletinsController
  def bulletin_params
    params.require(:exchange).permit(:title,
                                     :body)
  end
  
end

app/controllers/bulletins/jobs_controller.rb
class Bulletins::JobsController < BulletinsController

  def index
    @bulletins = Job.paginate(page: params[:page])

    respond_to do |format|
      format.json { render json: Job.all }
      format.html { render template: 'bulletins/shared/index' }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @bulletin = @current_user.jobs.build
    super
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @bulletin = current_user.jobs.build(bulletin_params)
    super
  end

  private

  def set_page_class
    @page_class = Job
  end

  # Note that this is also used in BulletinsController
  def bulletin_params
    params.require(:job).permit(:title,
                                :body)
  end

end

app/controllers/bulletins/lost_founds_controller.rb
class Bulletins::LostFoundsController < BulletinsController

  def index
    @bulletins = LostFound.paginate(page: params[:page])

    respond_to do |format|
      format.json { render json: LostFound.all }
      format.html { render template: 'bulletins/shared/index' }
    end
  end

  # GET /lost_founds/new
  # GET /lost_founds/new.json
  def new
    @bulletin = @current_user.lost_founds.build
    super
  end

  # POST /lost_founds
  # POST /lost_founds.json
  def create
    @bulletin = current_user.lost_founds.build(bulletin_params)
    super
  end

  private

  def set_page_class
    @page_class = LostFound
  end

  # Note that this is also used in BulletinsController
  def bulletin_params
    params.require(:lost_found).permit(:title,
                                       :body)
  end
  
end

app/controllers/bulletins/posts_controller.rb
class Bulletins::PostsController < ApplicationController

  def create
    # Thread creation
    unless params[:post][:discussion_id]
      @thread = current_user.discussions.build(title: params[:post][:title],
                                               last_active: Time.now)
      @post = current_user.posts.build(post_params)
      @post.discussion = @thread
      if @thread.valid? && @post.valid?
        @thread.save!
        @post.save!
        redirect_to @thread
      else
        @post.valid? # populate .errors without saving
        render "bulletins/discussions/new", :layout => 'discussions'
      end
    # Reply
    else
      @post = current_user.posts.create(post_params)
      respond_to do |format|
        format.js {}
      end
    end
  end

  def edit
    @post = Post.find_by(id: params[:id])
    if @post.user == current_user || current_user.admin?
      respond_to do |format|
        format.js {}
      end
    else
      redirect_to "/discussions"
    end
  end

  def update
    p = Post.find(params[:id])
    if p.user == current_user
      p.content = params[:post][:content]
      p.save
    end
    redirect_to p.discussion
  end

  def destroy
    @p = Post.find(params[:id])
    if current_user == @p.user || current_user.admin?
      # Note we're not actually deleting anything
      @p.deleted = true
      @p.save
      if !@p.discussion.children.any?
        @p.discussion.deleted = true
        @p.discussion.save
      end
      respond_to do |format|
        format.js {}
      end
    else
      redirect_to "/discussions"
    end
  end

  private

  def post_params
    params.require(:post).permit(:content, :title, :discussion_id)
  end

end

app/controllers/bulletins/rides_controller.rb
class Bulletins::RidesController < BulletinsController

  def index
    @bulletins = Ride.alive.paginate(page: params[:page])

    respond_to do |format|
      format.json { render json: Ride.all }
      format.html { render template: 'bulletins/shared/index' }
    end
  end

  def new
    @bulletin = current_user.rides.build
    super
  end

  def create
    @bulletin = current_user.rides.build(bulletin_params)
    super
  end

  private

  def set_page_class
    @page_class = Ride
  end
  
  def bulletin_params
    params.require(:ride).permit(:body,
                                 :source, 
                                 :destination,
                                 :start_date,
                                 :offer)
  end

end

app/controllers/bulletins_controller.rb
class BulletinsController < ApplicationController
  before_action :ensure_user, except: [:index, :show]

  before_action :ensure_valid_id, only: [:edit, :update, :destroy]
  before_action :ensure_ownership, only: [:edit, :update, :destroy]

  before_action :set_page_class # defined in subclass

  # A bulletin subclass can override this if wants to
  # display in a special way
  def show
    @bulletin = Bulletin.find(params[:id])

    respond_to do |format|
      format.html { render "bulletins/shared/show" }
      format.json { render json: @bulletin }
    end
  end

  def new
    # @bulletin must be set in subclass before calling this
    respond_to do |format|
      format.html { render "bulletins/shared/_form" }
      format.json { render json: @bulletin }
    end
  end

  def create
    # @bulletin must be set in subclass before calling this    
    if @bulletin.save
      respond_to do |format|
        format.html { redirect_to @bulletin }
        format.json { render json: @bulletin, status: :created }
      end
    else
      respond_to do|format|
        format.html { render "bulletins/shared/_form" }
        format.json { render json: @bulletin.errors, status: :unprocessable_entity }
      end
    end    
  end

  def edit
    render "bulletins/shared/_form"
  end

  def update
    respond_to do |format|
      if @bulletin.update_attributes(bulletin_params)
        format.html { redirect_to @bulletin, notice: 'Successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bulletin.errors, status: :unprocessable_entity }
      end
    end    
  end

  def destroy
    @bulletin.destroy
    redirect_to @bulletin.class
  end

  protected

  def ensure_valid_id
    @bulletin = Bulletin.find_by(id: params[:id])
    forbidden "Record does not exist" if @bulletin.nil?
  end

  def ensure_ownership
    forbidden "Permission denied" unless current_user.owns?(@bulletin)
  end

  def set_page_class
  end
end

app/helpers/bulletins_helper.rb
module BulletinsHelper
end

app/views/bulletins/shared/_form.html.erb
<% content_for :body_class, "announcement" %>

<article class="list-creation">
  <section>
    <%= form_for @bulletin do |f| %>
      <% if @bulletin.errors.any? %>
        <div id="error_explanation">
          <b><%= pluralize(@bulletin.errors.count, "error") %> prohibited this from being saved:</b>

          <ul>
            <% @bulletin.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <% if @bulletin.is_a? Ride # Display source and dest fields %>
        <div class="field">
          <%= f.label :offer do %>
            <%= f.check_box :offer %>
            I'm offering this ride
          <% end %>
        </div>

        <div class="field">
          <h5><%= f.label :source %></h5>
          <%= f.text_field :source %></h5>          
        </div>

        <div class="field">
          <h5><%= f.label :destination %></h5>
          <%= f.text_field :destination %></h5>
        </div>
      <% else # Display title field for everything but rides %>
        <div class="field">
          <h5><%= f.label :title %></h5>
          <%= f.text_field :title %>
        </div>
      <% end %>

      <% if [Announcement, Ride].include? @bulletin.class %>
        <div class="field">
        
          <% if @bulletin.is_a? Announcement %>
            <h5><%= f.label :show_my_post_starting_on %></h5>
          <% elsif @bulletin.is_a? Ride %>
            <h5><%= f.label :date %></h5>
          <% end %>

          <%= f.text_field :start_date, 
              value: @bulletin.try(:start_date).try(:strftime,'%b %d, %Y'),
              placeholder: Date.today.strftime("%b %d") %>
        </div>
      <% end %>

      <div class="field">
        <h5><%= f.label :message %></h5>
        <%= f.text_area :body %>
      </div>

      <%= f.submit 'Submit', :class => 'submit' %>
    <% end %>
  </section>
</article>

app/views/bulletins/shared/index.html.erb
<% content_for :head do %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"></meta>
<% end %>

<% content_for :body_class, "announcement" %>

<article class="main-table">
  <section>
    <% if @bulletins.empty? %>
      <h1 class="no-posts">No Posts</h1>
    <% else %>
      <table>
        <thead>
          <tr>
            <th class="col-60">Summary</th>
            <th class="col-6020">Posted by</th>
            <th class="col-20">Date Posted</th>
          </tr>
        </thead>
        <tbody>
          <% @bulletins.each do |bulletin| %>
            <tr>
              <td class="col-60">
                <%= link_to bulletin.title, bulletin %>
                <% if current_user.try(:owns?, bulletin) %>
                  [ <%= link_to 'Edit', [:edit, bulletin] %>
                  | <%= link_to "Delete", bulletin_path(bulletin), method: :delete, data: { confirm: "Are you sure?" } %>
                  ]
                <% end %>
              </td>
              <td class="col-20"><%= bulletin.user.name %></td>
              <td class="col-20"><%= bulletin.start_date.strftime('%B %d, %Y') %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= will_paginate @bulletins %>
    <% end %>
  </section>
</article>

app/views/bulletins/shared/show.html.erb
<% content_for :head do %>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"></meta>
<% end %>

<% content_for :body_class, "announcement" %>

<article class="list-creation">
  <section>
    <div class="field">
    <h3><%= @bulletin.title %></h3>
    
    <% if @bulletin.is_a? Ride %>
      <div>
        <b><%= @bulletin.start_date.strftime("%b %d") %><b>
      </div>
    <% end %>

    Posted
      <%= @bulletin.created_at.localtime.strftime("%A %B %e") %>
      by 
      <% if @bulletin.user.unix_id %>
         <%= link_to @bulletin.user.name, @bulletin.user %>
      <% else %>
         <%= @bulletin.user.name %>
      <% end %>
      <% if !current_user.nil? && (@bulletin.user == current_user || current_user.admin?) %>
        [ <%= link_to 'Edit', [:edit, @bulletin] %>
        | <%= link_to "Delete", bulletin_path(@bulletin), method: :delete, data: { confirm: "Are you sure?" } %> 
        ]
      <% end %>

    <br><br>
    <%= simple_format @bulletin.body %>
    </div>
    <br>
  </section>
</article>