config/routes.rb
WSOonRails::Application.routes.draw do

  resources :api_keys, only: :create

  # SESSIONS
  get  'account/login',      to: 'account#login_page'
  post 'account/login',      to: 'account#login',      as: :login
  get  'account/logout',     to: 'account#logout',     as: :logout

  # INDEX
  root  'front#index'
  match '/search',   to: 'front#search', via: [:get, :post]


  # FACEBOOK
  get  'facebook',                  to: 'facebook#index'
  post 'facebook',                  to: 'facebook#index'
  get 'facebook/edit',             to: 'facebook#edit'
  get 'facebook/help',              to: 'facebook#help'
  get 'facebook/view/:unix_id',    to: 'facebook#view'

  scope '/facebook' do
    resources :students, only: [:show, :edit, :update], controller: 'users', path: 'users'
    resources :professors, only: [:show, :edit, :update], controller: 'users', path: 'users'
    resources :staff, only: [:show, :edit, :update], controller: 'users', path: 'users'
    resources :alum, only: [:show, :edit, :update], controller: 'users', path: 'users'
  end


  # EPHCATCH
  get "/ephcatch", to: "ephcatch#index"
  scope "/ephcatch" do
    resources :ephcatches, controller: "ephcatch", path: "ephcatches"
    get 'matches', to: 'ephcatch#matches'
  end

  # BULLETINS
  resources :bulletins
  scope module: 'bulletins' do
    resources :announcements
    resources :discussions
    resources :posts
    resources :exchanges
    resources :jobs
    resources :lost_founds, path: "lost_and_found"
    resources :rides
  end
  resources :bulletins

  get 'bulletins', to: 'bulletins#index'

  # FACTRAK
  get  '/factrak',                         to: 'factrak#index'
  get  '/factrak/autocomplete',            to: 'factrak#autocomplete', as: 'autocomplete'
  get  '/factrak/find_depts_autocomplete', to: 'factrak#find_depts_autocomplete'
  get  '/factrak/moderate',                to: 'factrak#moderate'
  post '/factrak/search',                  to: 'factrak#search'
  post '/factrak/accept_policy',           to: 'factrak#accept_policy'
  get  '/factrak/policy',                  to: 'factrak#policy'
  get  '/factrak/flag',                    to: 'factrak#flag'
  get  '/factrak/unflag',                  to: 'factrak#unflag'

  namespace :factrak do
    resources :courses
    resources :areas_of_study
    resources :professors
    resources :factrak_agreements, path: '/agreements', as: 'agreements'
    resources :factrak_surveys,    path: '/surveys',    as: 'surveys'
  end


  # ABOUT
  get '/about', to: 'about#index'
  scope '/about' do
    get 'welcome', to: 'about#welcome'
    get 'listserv', to: 'about#listserv'
  end


  # DORMTRAK
  get  '/dormtrak',               to: 'dormtrak#index'
  post '/dormtrak/search',        to: 'dormtrak#search'
  get  '/dormtrak/policy',        to: 'dormtrak#policy'
  post '/dormtrak/accept_policy', to: 'dormtrak#accept_policy'

  namespace :dormtrak do
    # the reviews route is a little hacky trick. it allows dormtrak_review_path
    # because dormtrak_review becomes just reviews and everything is prepended
    # with the namespace dormtrak. So, it is really dormtrak..review_path, but
    # it looks like dormtrak_review..path :) so no dormtrak_dormtrak_review_path
    # which is ridiculous
    resources :dormtrak_reviews, path: '/reviews', as: 'reviews'
    resources :dorms, only: [:index, :show, :update]
    resources :neighborhoods, path: 'hoods', only: [:index, :show, :update]
  end

end

app/controllers/dormtrak/dorms_controller.rb
class Dormtrak::DormsController < ApplicationController
  include DormtrakHelper
  # Currently set to only allow people who've logged in
  before_action :ensure_authorization, only: [:show]
  before_action :ensure_authorization_for_index, only: :index
  before_action :ensure_student, only: [:new, :create]
  before_action :ensure_dormtrak_policy_acceptance, except: [:accept_policy, :policy]

  layout 'dormtrak'

  def index
    @dorms = Dorm.all
    @dorms = @dorms.take(params[:limit].to_i) if params[:limit]
    respond_to do |format|
      format.json { render json: @dorms }
    end
  end

  def show
    @dorm = Dorm.trakked.where("lower(name) = ?", params[:id].downcase).first

    respond_to do |format|
      format.html do
        if @dorm.nil?
          redirect_to '/dormtrak' and return
        end
        @reviews = @dorm.recent_reviews
      end
      
      format.json { render json: @dorm }
    end
  end

  def update
  end

  private

  def dorm_params
    params.require(:dorm).permit(:neighborhood_id,
                                 :number_reviews,
                                 :name,
                                 :key_or_card,
                                 :description,
                                 :built,
                                 :capacity,
                                 :number_bathrooms,
                                 :number_singles,
                                 :number_doubles,
                                 :number_washers,
                                 :seniors,
                                 :juniors,
                                 :sophomores,
                                 :freshmen,
                                 :bathroom_ratio,
                                 :comfort,
                                 :loudness,
                                 :convenience,
                                 :wifi,
                                 :location, 
                                 :satisfaction)
  end

end

app/controllers/dormtrak/dormtrak_reviews_controller.rb
class Dormtrak::DormtrakReviewsController < ApplicationController

  before_action :ensure_authorization, only: [:show]
  before_action :ensure_authorization_for_index, only: :index
  before_action :ensure_student
  before_action :ensure_dorm, only: [:new, :create]
  before_action :ensure_new_review, only: [:new, :create]
  before_action :ensure_ownership, only: [:edit, :update, :destroy]

  layout 'dormtrak'

  def index
    @reviews = DormtrakReview.all
    @reviews = @reviews.take(params[:limit].to_i) if params[:limit]
    respond_to do |format|
      format.json { render json: @reviews }
    end
  end

  def show
    @review = DormtrakReview.find_by(id: params[:id])
    respond_to do |format|
      format.json { render json: @review }
    end
  end

  def new
    @dorm = current_user.dorm
    @review = @dorm.dormtrak_reviews.build
  end

  def create
    # what if reviewing not their current one?
    @room = current_user.dorm_room
    @dorm = @room.dorm

    # Associate the review with the room
    @review = @dorm.dormtrak_reviews.build(review_params)
    @review.dorm_room = @room
    @review.user = current_user

    if @review.save
      flash[:success] = "Successfully saved review."
      redirect_to [:dormtrak, @dorm]
    else
      flash.now[:notice] = "Could not save review."
      render 'new'
    end
  end

  def edit
  end

  def update
    @review.comment = params[:dormtrak_review][:comment]
    @review.noise   = params[:dormtrak_review][:noise]

    if @review.save
      flash[:success] = "Comment updated."
      redirect_to '/dormtrak'
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    flash[:notice] = "Review deleted."
    redirect_to '/dormtrak'
  end
  
  protected

  def ensure_dorm
    unless current_user.dorm
      flash[:notice] = "You don't seem to have a dorm. If you actually do, contact us"
      redirect_to '/dormtrak'
    end
  end

  def ensure_new_review
    if current_user.has_reviewed_room?
      flash[:notice] = "You've already reviewed your room."
      redirect_to '/dormtrak'
    end    
  end

  def ensure_ownership
    @review = DormtrakReview.find(params[:id])
    unless current_user.can_edit_review(@review)
      flash[:notice] = "You do not have permission to do that."
      redirect_to '/dormtrak'
    end
  end

  private

  def review_params
    params.require(:dormtrak_review).permit(:user_id,
                                            :dorm_id,
                                            :room_id,
                                            :comment,
                                            :lived_here,
                                            :closet,
                                            :flooring,
                                            :common_room_access,
                                            :common_room_desc,
                                            :thermostat_access,
                                            :thermostat_desc,
                                            :outlets_desc,
                                            :key_or_card,
                                            :noise,
                                            :bed_adjustable,
                                            :anonymous,
                                            :capacity,
                                            :faces,
                                            :private_bathroom,
                                            :bathroom_desc,
                                            :picture,
                                            :comfort,
                                            :loudness,
                                            :convenience,
                                            :wifi, 
                                            :location,
                                            :satisfaction)
  end

end

app/controllers/dormtrak/neighborhoods_controller.rb
class Dormtrak::NeighborhoodsController < ApplicationController

  before_action :ensure_authorization, only: [:show]
  before_action :ensure_authorization_for_index, only: :index

  layout 'dormtrak'
  
  def index
    @neighborhoods = Neighborhood.all
    respond_to do |format|
      format.json { render json: @neighborhoods }
    end
  end

  def show    
    respond_to do |format|
      format.json do 
        @neighborhood = Neighborhood.where(id: params[:id]).first
        render json: @neighborhood
      end
      format.html do
        @neighborhood = Neighborhood.where("lower(name) = ?", params[:id].downcase).first
        redirect_to '/dormtrak' unless @neighborhood
      end
    end
  end

  def update
  end

end

app/controllers/dormtrak_controller.rb
class DormtrakController < ApplicationController
  # TODO: Auto update if everything is anonymous, but
  # all expired..
  include DormtrakHelper

  before_action :ensure_user
  before_action :ensure_dormtrak_policy_acceptance, except: [:accept_policy, :policy]

  def policy
  end

  def index
    @neighborhoods = Neighborhood.all
    @reviews = DormtrakReview.commented.limit(10)
    # Nicer for forms. Abridges long reviews...
    @abridged = true
  end

  def search
    q = params[:search]
    @dorms = Dorm.trakked.where("lower(name) LIKE ?", "%#{q.downcase}%")
    redirect_to [:dormtrak, @dorms.first] if @dorms.length == 1
  end

  def accept_policy
    if params[:accept] == "1"
      current_user.has_accepted_dormtrak_policy = true
      current_user.save
      redirect_to request.referer || { :action => :index }
    else
      redirect_to "/front/index"
    end
  end

end

app/helpers/dormtrak_helper.rb
module DormtrakHelper

  def photo_for(dorm)
    # Return main photo for that dorm
    path = "banners/#{dorm.name.titleize}.png"
    image_tag(path, title: "(photo by Doug Schiazza)", width: "100%")
  end

  def avatar_for(dorm)
    path = "avatars/#{dorm.name.titleize}.png"
    image_tag(path, title: dorm.name)
  end

  def small_avatar_for(dorm)
    # Each are 300 x 154. This is for recent comments
    path = "avatars/#{dorm.name.titleize}.png"
    image_tag(path, title: dorm.name, size: '150x77')
  end
end

app/views/dormtrak/_comment.html.erb
<li id="recent-comment">
  <%= link_to small_avatar_for(r.building), r.building %>
  <span class="comment"><%= r.comment %></span>
  <span class="timestamp">
    <%= time_ago_in_words(micropost.created_at) %> ago. jejejeje
  </span>
</li>

app/views/dormtrak/_rankings.html.erb
<% max = 3 %>

<article class="dorm-ranks">
  <h3>Rankings</h3>
  
  <table>
    <tr> 
      <th>Max Mean Single Size</th>
      <th>Min Mean Single Size</th>
    </tr>

    <% Dorm.order_biggest_singles.first(max).
        zip(Dorm.order_smallest_singles.first(max)).each do |a, b| %>
      <tr>
      	<td><%= link_to a.name, [:dormtrak, a] %> <br>
  	     (<%= a.average_single_area %> sq. ft.)
        </td> 
	      <td><%= link_to b.name, [:dormtrak, b] %> <br>
	       (<%= b.average_single_area %> sq. ft.)
       </td>
      </tr>
    <% end %>
  </table>
  
  <table>
    <tr> 
      <th>Biggest Singles</th>
      <th>Smallest Singles</th> 
    </tr>

    <% DormRoom.trakked.singles.biggest.first(max).
        zip(DormRoom.trakked.singles.smallest.first(max)).each do |a, b| %>
      <tr>
        <td>
          <%= link_to "#{a.dorm.name} #{a.number}", [:dormtrak, a.dorm] %>
          <br> 
          (<%= a.area %> sq. ft.)
        </td> 
        <td>
          <%= link_to "#{b.dorm.name} #{b.number}", [:dormtrak, b.dorm] %>
          <br> 
          (<%= b.area %> sq. ft.)
        </td>
      </tr>
    <% end %>
  </table>
  
  <table>
    <tr> 
      <th>Max Mean Double Size</th>
      <th>Min Mean Double Size</th> 
    </tr>

    <% Dorm.order_biggest_doubles.first(max).
        zip(Dorm.order_smallest_doubles.first(max)).each do |a, b| %>
      <tr>
        <td>
  	      <%= link_to a.name, [:dormtrak, a] %>
  	      <br> 
  	      (<%= a.average_double_area %> sq. ft.)
        </td> 
        <td>
          <%= link_to b.name, [:dormtrak, b] %>
  	      <br>
          (<%= b.average_double_area %> sq. ft.)
        </td>
      </tr>
    <% end %>
  </table>
  
  <table>
    <tr> 
      <th>Biggest Doubles</th>
      <th>Smallest Doubles</th> 
    </tr>

    <% DormRoom.trakked.doubles.biggest.first(max).
        zip(DormRoom.trakked.doubles.smallest.first(max)).each do |a, b| %>
      <tr>
        <td>
          <%= link_to "#{a.dorm.name} #{a.number}", [:dormtrak, a.dorm] %>
          <br>
          (<%= a.area %> sq. ft.)
        </td>         
        <td>
          <%= link_to "#{b.dorm.name} #{b.number}", [:dormtrak, b.dorm] %>
          <br>
          (<%= b.area %> sq. ft.)
        </td>
      </tr>
    <% end %>
  </table>
  
  <table>
    <tr> 
      <th>Most Singles</th>
      <th>Most Doubles</th> 
    </tr>

    <% Dorm.most_singles.first(max).zip(Dorm.most_doubles.first(max)).each do |a, b| %>
      <tr>
        <td><%= link_to a.name, [:dormtrak, a] %><br> (<%= a.number_singles %>)</td> 
        <td><%= link_to b.name, [:dormtrak, b] %><br> (<%= b.number_doubles %>)</td>
      </tr>
    <% end %>
  </table>
  
  <table>
    <tr> 
      <th>Most bathrooms</th> <th>Fewest bathrooms</th> 
    </tr>
    <% Dorm.most_bathrooms.take(max).zip(Dorm.fewest_bathrooms.take(max)).each do |a, b| %>
      <tr>
        <td><%= link_to a.name, [:dormtrak, a] %><br> (<%= a.bathroom_ratio.round(2) %>:1)</td>
        <td><%= link_to b.name, [:dormtrak, b] %><br> (<%= b.bathroom_ratio.round(2) %>:1)</td>
      </tr>
    <% end %>
  </table>

</article>

app/views/dormtrak/index.html.erb
<div class="container">
  <aside class="sidebar">
    <%= render 'rankings' %>
  </aside>

  <article class="main">
    <section class="lead">
      <h3>Welcome to Dormtrak</h3>
      <p>Dormtrak is a system where students can 
      <%= link_to "anonymously", dormtrak_policy_path %> 
      share their thoughts about dorm buildings and rooms, as well as find out
      everything there is to know about housing at Williams.
      Much of our information is pulled from surveys that students fill
      out, so by filling out the survey for your building, you help all of us 
      make the most informed decision we can about where to live.
      <% if current_user.try(:dorm_room) %>
        <% unless r = current_user.has_reviewed_room? %>
          <strong>To fill out the survey, click <%= link_to "here", new_dormtrak_review_path %></strong>.
         <% else %>
          You've already filled out a survey this year, but you can click <%= link_to 'here', edit_dormtrak_review_path(r) %> to edit it.
	      <% end %>
      <% end %>
      </p>
    </section>
    <section>
      <%= render 'dormtrak/shared/recent_comments' %>
    </section>
  </article>
</div>

app/views/dormtrak/policy.html.erb
<div class="article"> 
  <section>
    <article>
      <h3>Policy</h3>
      <% if !current_user.has_accepted_dormtrak_policy? %>
      <p class="intro-paragraph">To proceed, read the policy below, then click Agree</p>
      <% end %>

      <br>
      
      <p> 
	Comments should be true, and based on personal experience. You can only
	review your current room and building, but that may change in the future.
      </p>
      <p>
	Currently, we do not have enough
	information on Co-op or First-year housing to make them available.
      </p>
      <p>
	When you post a review, you'll see an option for making it anonymous.
	If you choose to make your review anonymous, we will hide both your 
	noise and general comment until the next school year. 
      </p>
      <p>
	While Dormtrak is designed to be as open as possible, inappropriate comments 
	will not be tolerated, and comments can be removed or edited at the discretion 
	of the student moderator to bring them into accordance with this policy. 
	Inappropriate comments include, but are not limited to, comments that name 
	other students, that contain racial or ethnic slurs, and those that harass 
	others. Spamming a building or room with incorrect information, for example
	in an effort to dissuade others from potentially choosing that dorm, will
	result in being banned from further use of Dormtrak. 
      </p>
      <p>
	You are allowed a max of one review per room. You can edit and delete your 
	reviews, but when you delete your review we hold onto some of the statistical
	information you provide us (like whether or not your room has a keypad to
	get in). 
      </p>
      <p>
	By using Dormtrak, you agree to abide by this policy.
      </p>
      
      <% if current_user.has_accepted_dormtrak_policy? %>
      <p> You have already accepted the Dormtrak policy.</p>
      <% else %>
      <%= form_tag(dormtrak_accept_policy_path) do %>
      <p><%= check_box_tag :accept %> I agree to the Dormtrak policy.</p>
      <%= submit_tag :continue %>
      <% end %>
      <% end %>
    </article>
  </section>
</div>

app/views/dormtrak/search.html.erb
<article class="facebook-results">
  <section>
    <% if @dorms.empty? %>
      <br>
      <h1 class="no-matches-found">
        No matches were found.
      </h1>
    <% else %>
      <table>
	<thead>
	  <tr>
	    <th>Building</th>
	    <th>Neighborhood</th>
	  </tr>
	</thead>
	<tbody>
	  <% @dorms.each do |dorm| %>
	    <tr>
	      <td><%= link_to dorm.name, [:dormtrak, dorm] %></td>
	      <% n = dorm.neighborhood %>
	      <td><%= link_to n.name, [:dormtrak, n] %></td>
	    </tr>
          <% end %>
	</tbody>
      </table>
    <% end %>
  </section>
</article>